In [1]:
import numpy as np

# 1. Создание массива
arr1 = np.arange(20)
print("1. arr1:\n", arr1)

# 2. Преобразование в 5x4
arr2 = arr1.reshape((5, 4))
print("\n2. arr2 (5x4):\n", arr2)

# 3. Слайсинг
sub1 = arr2[:, 1]  # Все строки, второй столбец (индекс 1)
print("\n3.1. Второй столбец (sub1):\n", sub1)

sub2 = arr2[-1, :] # Последняя строка, все столбцы
print("\n3.2. Последняя строка (sub2):\n", sub2)

sub3 = arr2[1:4, 0:3] # Строки с 1 по 3, столбцы с 0 по 2
print("\n3.3. Внутренний квадрат 3x3 (sub3):\n", sub3)

# 4. Изменение формы (порядок Fortran)
arr3 = arr2.reshape((20,), order='F')
print("\n4. arr3 (по столбцам):\n", arr3)

1. arr1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

2. arr2 (5x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

3.1. Второй столбец (sub1):
 [ 1  5  9 13 17]

3.2. Последняя строка (sub2):
 [16 17 18 19]

3.3. Внутренний квадрат 3x3 (sub3):
 [[ 4  5  6]
 [ 8  9 10]
 [12 13 14]]

4. arr3 (по столбцам):
 [ 0  4  8 12 16  1  5  9 13 17  2  6 10 14 18  3  7 11 15 19]


In [2]:
import numpy as np

# 1. Скалярное произведение векторов
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product_1 = np.dot(a, b)
dot_product_2 = a @ b
print("1. Скалярное произведение:")
print("   np.dot:", dot_product_1)
print("       @ :", dot_product_2)

# 2. Умножение матриц
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

matrix_product = A @ B
print("\n2. Умножение матриц A на B:\n", matrix_product)

# 3. Решение системы уравнений
# Матрица коэффициентов
A_sys = np.array([[2, 1], [1, -3]])
# Вектор правой части
B_sys = np.array([5, -1])

# Решение системы
X_solution = np.linalg.solve(A_sys, B_sys)
print("\n3. Решение системы уравнений:")
print("   X = [x, y] =", X_solution)

# Проверка (должно быть [5, -1])
check = A_sys @ X_solution
print("   Проверка A_sys @ X_solution =", check)

1. Скалярное произведение:
   np.dot: 32
       @ : 32

2. Умножение матриц A на B:
 [[19 22]
 [43 50]]

3. Решение системы уравнений:
   X = [x, y] = [2. 1.]
   Проверка A_sys @ X_solution = [ 5. -1.]


In [3]:
import numpy as np

# 1. Генерация данных
np.random.seed(42)  # Для воспроизводимости результата
scores = np.random.randint(50, 101, size=(30, 4))
print("1. Массив оценок (shape):", scores.shape)

# 2. Расчет статистик
mean_per_student = np.mean(scores, axis=1) # Среднее по строке (по каждому студенту)
max_per_subject = np.max(scores, axis=0)   # Максимум по столбцу (по каждому предмету)
std_all = np.std(scores)                   # Стандартное отклонение по всему массиву
top_student_index = np.argmax(mean_per_student) # Индекс студента с макс. средним

print("\n2. Статистика:")
print("   Средний балл каждого студента:\n", mean_per_student)
print("   Максимальный балл по каждому предмету:\n", max_per_subject)
print("   Стандартное отклонение по всем оценкам:", std_all)
print("   Индекс лучшего студента:", top_student_index)

# 3. Нормализация (Z-score по каждому студенту)
# Сначала расширим массив средних значений до размеров исходного,
# чтобы можно было выполнить поэлементные операции.
mean_expanded = mean_per_student[:, np.newaxis] # Теперь shape (30, 1)
std_per_student = np.std(scores, axis=1)[:, np.newaxis] # Std по каждому студенту

normalized_scores = (scores - mean_expanded) / std_per_student
print("\n3. Нормализованные оценки (первые 5 строк):\n", normalized_scores[:5])

1. Массив оценок (shape): (30, 4)

2. Статистика:
   Средний балл каждого студента:
 [80.5  70.75 66.25 74.75 72.   71.75 76.75 84.75 75.5  82.75 71.   70.5
 73.75 73.25 75.5  74.5  73.   69.25 79.5  71.75 70.25 74.   82.5  83.25
 71.5  65.25 68.25 70.75 76.   86.5 ]
   Максимальный балл по каждому предмету:
 [100 100  96  96]
   Стандартное отклонение по всем оценкам: 14.74953859918638
   Индекс лучшего студента: 29

3. Нормализованные оценки (первые 5 строк):
 [[ 0.69411722 -0.23137241 -1.52705788  1.06431307]
 [-1.23634533 -0.06743702  1.55105141 -0.24726907]
 [ 0.91853152 -0.99840383 -0.99840383  1.07827614]
 [ 0.71210181  0.9899952  -0.12157836 -1.58051865]
 [-0.06726728 -1.41261287  0.06726728  1.41261287]]


In [4]:
import numpy as np

# 1. Генерация данных
np.random.seed(123)
data = np.random.randn(10, 10)
print("1. Исходный массив data (первые 3x3):\n", data[:3, :3])

# 2. Создание маски
outlier_mask = np.abs(data) > 1
print(f"\n2. Маска 'выбросов' (первые 3x3):\n{outlier_mask[:3, :3]}")
print(f"   Количество выбросов: {np.sum(outlier_mask)}")

# 3. Замена выбросов
# Создаем копию, чтобы не испортить исходные данные
data_clean = data.copy()

# Маски для положительных и отрицательных выбросов
positive_outliers = outlier_mask & (data > 0)
negative_outliers = outlier_mask & (data < 0)

# Замена
data_clean[positive_outliers] = 1
data_clean[negative_outliers] = -1

print("\n3. Очищенный массив (первые 3x3):\n", data_clean[:3, :3])
print(f"   Проверка: макс. значение в очищенном массиве: {np.max(data_clean)}")
print(f"   Проверка: мин. значение в очищенном массиве: {np.min(data_clean)}")

# 4. Создание цветового массива с помощью np.select
conditions = [data > 1, data < -1]
choices = ['red', 'blue']

# Значение по умолчанию, если ни одно условие не выполнено
colors = np.select(conditions, choices, default='gray')

print("\n4. Цветовой массив (первые 3x3):")
# Выводим в виде списка для наглядности
for row in colors[:3]:
    print("   ", row[:3])

1. Исходный массив data (первые 3x3):
 [[-1.0856306   0.99734545  0.2829785 ]
 [-0.67888615 -0.09470897  1.49138963]
 [ 0.73736858  1.49073203 -0.93583387]]

2. Маска 'выбросов' (первые 3x3):
[[ True False False]
 [False False  True]
 [False  True False]]
   Количество выбросов: 44

3. Очищенный массив (первые 3x3):
 [[-1.          0.99734545  0.2829785 ]
 [-0.67888615 -0.09470897  1.        ]
 [ 0.73736858  1.         -0.93583387]]
   Проверка: макс. значение в очищенном массиве: 1.0
   Проверка: мин. значение в очищенном массиве: -1.0

4. Цветовой массив (первые 3x3):
    ['blue' 'gray' 'gray']
    ['gray' 'gray' 'red']
    ['gray' 'red' 'gray']
