In [2]:
a = [[1, 2, 3], [4, 5, 6], [7, 8]]
a

[[1, 2, 3], [4, 5, 6], [7, 8]]

In [6]:
import numpy as np

print("=== ДЕМОНСТРАЦИЯ NUMPY ===\n")

# 1. Создание массивов
print("1. Создание массивов:")
# Одномерный массив
arr1d = np.array([1, 2, 3, 4, 5])
print(f"Одномерный массив: {arr1d}")

# Двумерный массив (матрица)
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Двумерный массив:\n{arr2d}")

# Специальные массивы
zeros = np.zeros((3, 3))+10
ones = np.ones((2, 4))*10
range_arr = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
random_arr = np.random.rand(3, 3)  # случайные числа

print(f"Массив нулей:\n{zeros}")
print(f"Массив единиц:\n{ones}")
print(f"Массив диапазона: {range_arr}")
print(f"Случайный массив:\n{random_arr}")

# 2. Математические операции
print("\n2. Математические операции:")
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(f"a + b = {a + b}")  # Поэлементное сложение
print(f"a * b = {a * b}")  # Поэлементное умножение
print(f"sin(a) = {np.sin(a)}")  # Математические функции
print(f"Сумма a: {np.sum(a)}")
print(f"Среднее a: {np.mean(a)}")

# 3. Индексация и срезы
print("\n3. Индексация и срезы:")
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Исходная матрица:\n{matrix}")
print(f"matrix[1, 2] = {matrix[1, 2]}")  # Элемент во 2-й строке, 3-м столбце
print(f"matrix[:, 1] = {matrix[:, 1]}")  # Второй столбец
print(f"matrix[1:, :2] =\n{matrix[1:, :2]}")  # Срез

# 4. Фильтрация
print("\n4. Фильтрация:")
data = np.array([1, 5, 2, 8, 3, 10, 4])
filtered = data[data > 4]
print(f"Исходные данные: {data}")
print(f"Элементы > 4: {filtered}")

# 5. Формы и преобразования
print("\n5. Формы и преобразования:")
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(f"Исходная форма: {arr.shape}")
print(f"Измененная форма:\n{arr.reshape(2, 3)}")

=== ДЕМОНСТРАЦИЯ NUMPY ===

1. Создание массивов:
Одномерный массив: [1 2 3 4 5]
Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Массив нулей:
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
Массив единиц:
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]]
Массив диапазона: [0 2 4 6 8]
Случайный массив:
[[0.00505099 0.42112548 0.69108765]
 [0.50396451 0.77492202 0.65464492]
 [0.46061903 0.94951741 0.75354852]]

2. Математические операции:
a + b = [11 22 33 44]
a * b = [ 10  40  90 160]
sin(a) = [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Сумма a: 10
Среднее a: 2.5

3. Индексация и срезы:
Исходная матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix[1, 2] = 6
matrix[:, 1] = [2 5 8]
matrix[1:, :2] =
[[4 5]
 [7 8]]

4. Фильтрация:
Исходные данные: [ 1  5  2  8  3 10  4]
Элементы > 4: [ 5  8 10]

5. Формы и преобразования:
Исходная форма: (3, 2)
Измененная форма:
[[1 2 3]
 [4 5 6]]


In [10]:
import pandas as pd

print("\n=== ДЕМОНСТРАЦИЯ PANDAS ===\n")

# 1. Чтение данных из файлов
print("1. Чтение данных:")
df_csv = pd.read_csv('/Users/ivan7chuk/Documents/example_numpy.csv')
print("Данные из CSV:")
print(df_csv)

df_json = pd.read_json('/Users/ivan7chuk/Documents/example_numpy.json')
print("\nДанные из JSON:")
print(df_json)

# 2. Обзор данных
print("\n2. Обзор данных:")
print(f"Форма DataFrame: {df_csv.shape}")
print(f"Столбцы: {list(df_csv.columns)}")
print(f"Типы данных:\n{df_csv.dtypes}")
print(f"Первые 3 строки:\n{df_csv.head(3)}")

# 3. Индексация и выбор данных
print("\n3. Выбор данных:")
print(f"Колонка 'name':\n{df_csv['name']}")
print(f"\nСтроки 1-2:\n{df_csv.iloc[1:3]}")
print(f"\nСтроки где age > 30:\n{df_csv[df_csv['age'] > 30]}")

# 4. Добавление и удаление столбцов
print("\n4. Модификация данных:")
df_csv['experience'] = [3, 5, 2, 4, 1]  # новый столбец
df_csv['bonus'] = df_csv['salary'] * 0.1  # расчёт на основе существующего
print("После добавления столбцов:")
print(df_csv[['name', 'salary', 'bonus']])

# Удаление столбца
df_csv.drop('bonus', axis=1, inplace=True)

# 5. Агрегация и группировка
print("\n5. Агрегация:")
print(f"Средняя зарплата: {df_csv['salary'].mean():.0f}")
print(f"Максимальная зарплата: {df_csv['salary'].max()}")

grouped = df_csv.groupby('city')['salary'].mean()
print(f"\nСредняя зарплата по городам:\n{grouped}")

# 6. Обработка пропущенных значений
print("\n6. Обработка NaN:")
df_with_nan = df_csv.copy()
df_with_nan.loc[0, 'salary'] = np.nan  # искусственно добавляем NaN
print(f"С NaN:\n{df_with_nan[['name', 'salary']]}")
print(f"Заполнение NaN средним:\n{df_with_nan['salary'].fillna(df_with_nan['salary'].mean())}")

# 7. Сохранение данных
print("\n7. Сохранение в файлы:")
df_csv.to_csv('output.csv', index=False)
df_csv.to_excel('output.xlsx', index=False)
print("Данные сохранены в output.csv и output.xlsx")



=== ДЕМОНСТРАЦИЯ PANDAS ===

1. Чтение данных:
Данные из CSV:
      name  age              city  salary
0    Alice   28            Moscow   75000
1      Bob   34  Saint Petersburg   82000
2  Charlie   29             Kazan   68000
3    Diana   31       Novosibirsk   71000
4      Eve   27     Yekaterinburg   69000

Данные из JSON:
    name  age              city  salary
0  Alice   28            Moscow   75000
1    Bob   34  Saint Petersburg   82000

2. Обзор данных:
Форма DataFrame: (5, 4)
Столбцы: ['name', 'age', 'city', 'salary']
Типы данных:
name      object
age        int64
city      object
salary     int64
dtype: object
Первые 3 строки:
      name  age              city  salary
0    Alice   28            Moscow   75000
1      Bob   34  Saint Petersburg   82000
2  Charlie   29             Kazan   68000

3. Выбор данных:
Колонка 'name':
0      Alice
1        Bob
2    Charlie
3      Diana
4        Eve
Name: name, dtype: object

Строки 1-2:
      name  age              city  salary
1  

In [14]:
import numpy as np
import os

# Создаем директорию
if not os.path.exists('numpy_data'):
    os.makedirs('numpy_data')

# Генерация финансовых данных чисто на NumPy
np.random.seed(42)

# Параметры
n_records = 100
companies = ['AAPL', 'GOOGL', 'MSFT', 'TSLA', 'AMZN']
n_companies = len(companies)

# Создаем структурированный массив NumPy
dtype = [
    ('date', 'U10'),
    ('company', 'U10'),
    ('open_price', 'f8'),
    ('close_price', 'f8'),
    ('volume', 'i8'),
    ('pe_ratio', 'f8'),
    ('dividend_yield', 'f8')
]

# Генерация данных
financial_data = np.zeros(n_records, dtype=dtype)

for i in range(n_records):
    company = companies[i % n_companies]
    base_price = np.random.uniform(50, 500)
    
    financial_data[i] = (
        f'2024-01-{(i % 30) + 1:02d}',  # date
        company,                        # company
        round(base_price, 2),           # open_price
        round(base_price * np.random.uniform(0.95, 1.05), 2),  # close_price
        np.random.randint(1000000, 50000000),  # volume
        round(np.random.uniform(10, 40), 2),   # pe_ratio
        round(np.random.uniform(0, 0.05), 4)   # dividend_yield
    )

# Сохраняем в CSV чисто средствами NumPy
header = 'date,company,open_price,close_price,volume,pe_ratio,dividend_yield'
np.savetxt('numpy_data/stock_data_numpy.csv', financial_data, 
           fmt='%s,%s,%.2f,%.2f,%d,%.2f,%.4f',
           header=header, comments='')

print("Данные сгенерированы и сохранены чисто на NumPy!")
print("Первые 5 записей:")
for i in range(5):
    print(financial_data[i])

Данные сгенерированы и сохранены чисто на NumPy!
Первые 5 записей:
('2024-01-01', 'AAPL', 218.54, 228.39, 22081788, 27.91, 0.0223)
('2024-01-02', 'GOOGL', 94.99, 94.6, 24981428, 28.03, 0.0354)
('2024-01-03', 'MSFT', 59.26, 62.05, 19544107, 38.16, 0.0)
('2024-01-04', 'TSLA', 496.5, 502.33, 10784633, 25.74, 0.0216)
('2024-01-05', 'AMZN', 181.05, 183.08, 47792155, 39.21, 0.0116)


In [16]:
import numpy as np

print("=== ЧИСТЫЙ NUMPY АНАЛИЗ ===\n")

# Загрузка данных чисто NumPy
data = np.genfromtxt('numpy_data/stock_data_numpy.csv', 
                     delimiter=',', dtype=None, names=True, encoding='utf-8')

print("1. ОБЗОР ДАННЫХ:")
print(f"Размер данных: {data.shape}")
print(f"Поля: {data.dtype.names}")
print(f"\nПервые 3 записи:")
for i in range(3):
    print(data[i])

# 2. БАЗОВЫЕ СТАТИСТИКИ
print("\n" + "="*50)
print("2. БАЗОВЫЕ СТАТИСТИКИ")

close_prices = data['close_price']
open_prices = data['open_price']
volumes = data['volume']
pe_ratios = data['pe_ratio']
dividends = data['dividend_yield']

print(f"Средняя цена закрытия: {np.mean(close_prices):.2f}")
print(f"Медианная цена: {np.median(close_prices):.2f}")
print(f"Стандартное отклонение цен: {np.std(close_prices):.2f}")
print(f"Минимальная цена: {np.min(close_prices):.2f}")
print(f"Максимальная цена: {np.max(close_prices):.2f}")

# 3. РАСЧЕТ ДОХОДНОСТИ
print("\n" + "="*50)
print("3. РАСЧЕТ ДОХОДНОСТИ")

daily_returns = ((close_prices - open_prices) / open_prices) * 100
print(f"Средняя дневная доходность: {np.mean(daily_returns):.2f}%")
print(f"Волатильность: {np.std(daily_returns):.2f}%")

# 4. ФИЛЬТРАЦИЯ
print("\n" + "="*50)
print("4. ФИЛЬТРАЦИЯ ДАННЫХ")

# Акции с доходностью > 2%
high_return_mask = daily_returns > 2.0
high_return_data = data[high_return_mask]
print(f"Акции с доходностью > 2%: {len(high_return_data)}")

# Недооцененные акции (P/E < 15)
undervalued_mask = pe_ratios < 15
undervalued_data = data[undervalued_mask]
print(f"Недооцененные акции (P/E < 15): {len(undervalued_data)}")

# Акции с дивидендами
dividend_mask = dividends > 0.02
dividend_data = data[dividend_mask]
print(f"Акции с дивидендами > 2%: {len(dividend_data)}")

# 5. СТАТИСТИЧЕСКИЙ АНАЛИЗ
print("\n" + "="*50)
print("5. СТАТИСТИЧЕСКИЙ АНАЛИЗ")

# Z-score для выявления аномалий
z_scores = (daily_returns - np.mean(daily_returns)) / np.std(daily_returns)
anomalies_mask = np.abs(z_scores) > 2
anomalies = data[anomalies_mask]
print(f"Аномальные движения (|Z-score| > 2): {len(anomalies)}")

# Value at Risk (95%)
var_95 = np.percentile(daily_returns, 5)
print(f"Value at Risk (95%): {var_95:.2f}%")

# 6. ГРУППИРОВКА ПО КОМПАНИЯМ (на NumPy)
print("\n" + "="*50)
print("6. АНАЛИЗ ПО КОМПАНИЯМ")

companies = np.unique(data['company'])
print("\nСтатистика по компаниям:")
print("Компания | Ср.цена | Ср.доходность | Ср.P/E")

for company in companies:
    company_mask = data['company'] == company
    company_data = data[company_mask]
    
    avg_price = np.mean(company_data['close_price'])
    avg_return = np.mean(daily_returns[company_mask])
    avg_pe = np.mean(company_data['pe_ratio'])
    
    print(f"{company:8} | {avg_price:7.2f} | {avg_return:13.2f}% | {avg_pe:6.2f}")

# 7. КОНКАТЕНАЦИЯ ДАННЫХ
print("\n" + "="*50)
print("7. КОНКАТЕНАЦИЯ И СОХРАНЕНИЕ")

# Создаем новый массив с добавленными полями
new_dtype = data.dtype.descr + [('daily_return', 'f8'), ('z_score', 'f8'), ('is_anomaly', 'bool')]
enhanced_data = np.zeros(data.shape, dtype=new_dtype)

# Копируем существующие данные
for field in data.dtype.names:
    enhanced_data[field] = data[field]

# Добавляем новые поля
enhanced_data['daily_return'] = daily_returns
enhanced_data['z_score'] = z_scores
enhanced_data['is_anomaly'] = anomalies_mask

# Сохраняем обогащенные данные
header_enhanced = 'date,company,open_price,close_price,volume,pe_ratio,dividend_yield,daily_return,z_score,is_anomaly'
np.savetxt('numpy_data/enhanced_data_numpy.csv', enhanced_data, 
           fmt='%s,%s,%.2f,%.2f,%d,%.2f,%.4f,%.2f,%.2f,%s',
           header=header_enhanced, comments='')

print("Обогащенные данные сохранены!")

# 8. КОМПЛЕКСНАЯ ФИЛЬТРАЦИЯ
print("\n" + "="*50)
print("8. КОМПЛЕКСНАЯ ФИЛЬТРАЦИЯ")

# Идеальные акции: недооцененные + положительная доходность + не аномальные
ideal_mask = (
    (pe_ratios < 20) & 
    (daily_returns > 0) & 
    (np.abs(z_scores) < 1.5) &
    (dividends > 0.01)
)

ideal_stocks = data[ideal_mask]
print(f"Найдено идеальных акций: {len(ideal_stocks)}")

if len(ideal_stocks) > 0:
    print("\nРекомендуемые акции:")
    for stock in ideal_stocks:
        return_pct = ((stock['close_price'] - stock['open_price']) / stock['open_price']) * 100
        print(f"  {stock['company']}: цена {stock['close_price']:.2f}, доходность {return_pct:.2f}%, P/E {stock['pe_ratio']:.2f}")

print(f"\nАнализ завершен! Обработано {len(data)} записей.")

=== ЧИСТЫЙ NUMPY АНАЛИЗ ===

1. ОБЗОР ДАННЫХ:
Размер данных: (100,)
Поля: ('date', 'company', 'open_price', 'close_price', 'volume', 'pe_ratio', 'dividend_yield')

Первые 3 записи:
('2024-01-01', 'AAPL', 218.54, 228.39, 22081788, 27.91, 0.0223)
('2024-01-02', 'GOOGL', 94.99, 94.6, 24981428, 28.03, 0.0354)
('2024-01-03', 'MSFT', 59.26, 62.05, 19544107, 38.16, 0.0)

2. БАЗОВЫЕ СТАТИСТИКИ
Средняя цена закрытия: 276.51
Медианная цена: 276.34
Стандартное отклонение цен: 132.34
Минимальная цена: 54.64
Максимальная цена: 502.33

3. РАСЧЕТ ДОХОДНОСТИ
Средняя дневная доходность: 0.28%
Волатильность: 3.07%

4. ФИЛЬТРАЦИЯ ДАННЫХ
Акции с доходностью > 2%: 35
Недооцененные акции (P/E < 15): 16
Акции с дивидендами > 2%: 61

5. СТАТИСТИЧЕСКИЙ АНАЛИЗ
Аномальные движения (|Z-score| > 2): 0
Value at Risk (95%): -4.55%

6. АНАЛИЗ ПО КОМПАНИЯМ

Статистика по компаниям:
Компания | Ср.цена | Ср.доходность | Ср.P/E
AAPL     |  256.99 |          0.10% |  26.25
AMZN     |  296.75 |          0.83% |  24.00
GOOG

In [17]:
import pandas as pd
import numpy as np
import os

print("=== ЧИСТЫЙ PANDAS АНАЛИЗ ===\n")

# Создаем тестовые данные чисто Pandas
if not os.path.exists('pandas_data'):
    os.makedirs('pandas_data')

# Генерация данных
np.random.seed(123)
n_records = 100

data = {
    'date': pd.date_range('2024-01-01', periods=n_records),
    'company': np.random.choice(['AAPL', 'GOOGL', 'MSFT', 'TSLA', 'AMZN'], n_records),
    'sector': np.random.choice(['Tech', 'Auto', 'Retail'], n_records),
    'open_price': np.round(np.random.uniform(50, 500, n_records), 2),
    'close_price': np.round(np.random.uniform(45, 550, n_records), 2),
    'volume': np.random.randint(1000000, 50000000, n_records),
    'pe_ratio': np.round(np.random.uniform(10, 40, n_records), 2),
    'dividend_yield': np.round(np.random.uniform(0, 0.05, n_records), 4)
}

df = pd.DataFrame(data)

# Добавляем немного логики в цены
df['close_price'] = df['open_price'] * np.random.uniform(0.9, 1.1, n_records)

# Сохраняем исходные данные
df.to_csv('pandas_data/stock_data_pandas.csv', index=False)

print("1. ЗАГРУЗКА И ОБЗОР ДАННЫХ:")
df = pd.read_csv('pandas_data/stock_data_pandas.csv')
print(f"Размер данных: {df.shape}")
print(f"\nИнформация о данных:")
print(df.info())
print(f"\nПервые 5 записей:")
print(df.head())

# 2. БАЗОВЫЙ АНАЛИЗ PANDAS
print("\n" + "="*50)
print("2. БАЗОВЫЙ АНАЛИЗ")

print("Статистика по числовым колонкам:")
print(df.describe())

print(f"\nКоличество записей по компаниям:")
print(df['company'].value_counts())

# 3. ДОБАВЛЕНИЕ ВЫЧИСЛЯЕМЫХ ПОЛЕЙ
print("\n" + "="*50)
print("3. ВЫЧИСЛЯЕМЫЕ ПОЛЯ")

df['daily_return'] = ((df['close_price'] - df['open_price']) / df['open_price']) * 100
df['price_range'] = df['close_price'] - df['open_price']
df['is_profitable'] = df['daily_return'] > 0

print("Данные с добавленными полями:")
print(df[['company', 'open_price', 'close_price', 'daily_return', 'is_profitable']].head())

# 4. ФИЛЬТРАЦИЯ PANDAS
print("\n" + "="*50)
print("4. ФИЛЬТРАЦИЯ")

# Простые фильтры
high_return = df[df['daily_return'] > 3.0]
print(f"Акции с доходностью > 3%: {len(high_return)}")

undervalued = df[df['pe_ratio'] < 15]
print(f"Недооцененные акции (P/E < 15): {len(undervalued)}")

# Сложные фильтры
good_dividends = df[(df['dividend_yield'] > 0.02) & (df['daily_return'] > 0)]
print(f"Акции с дивидендами > 2% и положительной доходностью: {len(good_dividends)}")

# 5. ГРУППИРОВКА И АГРЕГАЦИЯ
print("\n" + "="*50)
print("5. ГРУППИРОВКА И АГРЕГАЦИЯ")

# Группировка по компаниям
company_stats = df.groupby('company').agg({
    'close_price': ['mean', 'std', 'min', 'max'],
    'daily_return': 'mean',
    'volume': 'sum',
    'pe_ratio': 'median'
}).round(2)

company_stats.columns = ['avg_price', 'price_std', 'min_price', 'max_price', 'avg_return', 'total_volume', 'median_pe']
print("Статистика по компаниям:")
print(company_stats)

# Группировка по секторам
sector_analysis = df.groupby('sector').agg({
    'daily_return': ['mean', 'std'],
    'pe_ratio': 'mean',
    'dividend_yield': 'mean'
}).round(3)

print("\nАнализ по секторам:")
print(sector_analysis)

# 6. СОРТИРОВКА
print("\n" + "="*50)
print("6. СОРТИРОВКА ДАННЫХ")

# Топ акций по доходности
top_performers = df.nlargest(5, 'daily_return')[['company', 'sector', 'daily_return', 'pe_ratio']]
print("Топ-5 акций по доходности:")
print(top_performers)

# Акции с наименьшим P/E
cheapest = df.nsmallest(5, 'pe_ratio')[['company', 'pe_ratio', 'daily_return']]
print("\nТоп-5 самых дешевых акций (по P/E):")
print(cheapest)

# 7. PIVOT ТАБЛИЦЫ
print("\n" + "="*50)
print("7. PIVOT ТАБЛИЦЫ")

# Сводная таблица: средняя доходность по компаниям и секторам
pivot_return = df.pivot_table(
    values='daily_return', 
    index='company', 
    columns='sector', 
    aggfunc='mean',
    fill_value=0
).round(2)

print("Средняя доходность по компаниям и секторам:")
print(pivot_return)

# 8. ОБРАБОТКА ВРЕМЕННЫХ РЯДОВ
print("\n" + "="*50)
print("8. АНАЛИЗ ВРЕМЕННЫХ РЯДОВ")

df['date'] = pd.to_datetime(df['date'])
df = df.sort_values('date')

# Добавляем недельные группы
df['week'] = df['date'].dt.isocalendar().week

# Анализ по неделям
weekly_analysis = df.groupby('week').agg({
    'daily_return': 'mean',
    'volume': 'sum',
    'company': 'count'
}).rename(columns={'company': 'trade_count'}).round(2)

print("Анализ по неделям:")
print(weekly_analysis)

# 9. КОНКАТЕНАЦИЯ DATA FRAMES
print("\n" + "="*50)
print("9. КОНКАТЕНАЦИЯ")

# Создаем дополнительный DataFrame с фундаментальными показателями
fundamental_data = pd.DataFrame({
    'company': ['AAPL', 'GOOGL', 'MSFT', 'TSLA', 'AMZN'],
    'market_cap_billion': [2800, 1800, 2200, 800, 1600],
    'employees': [164000, 156500, 221000, 127855, 1541000],
    'founded_year': [1976, 1998, 1975, 2003, 1994]
})

# Объединяем с основными данными
enhanced_df = df.merge(fundamental_data, on='company', how='left')
print("Данные после объединения с фундаментальными показателями:")
print(enhanced_df[['company', 'sector', 'daily_return', 'market_cap_billion']].head())

# 10. СОХРАНЕНИЕ РЕЗУЛЬТАТОВ
print("\n" + "="*50)
print("10. СОХРАНЕНИЕ РЕЗУЛЬТАТОВ")

# Сохраняем различные результаты
enhanced_df.to_csv('pandas_data/enhanced_analysis.csv', index=False)
company_stats.to_csv('pandas_data/company_statistics.csv')
top_performers.to_csv('pandas_data/top_performers.csv', index=False)

print("Результаты сохранены:")
print("- enhanced_analysis.csv - обогащенные данные")
print("- company_statistics.csv - статистика по компаниям") 
print("- top_performers.csv - лучшие акции")

# 11. ПРОДВИНУТАЯ ФИЛЬТРАЦИЯ
print("\n" + "="*50)
print("11. ПРОДВИНУТАЯ ФИЛЬТРАЦИЯ С QUERY")

# Используем метод query для сложных условий
ideal_stocks = df.query(
    'pe_ratio < 20 and daily_return > 0 and dividend_yield > 0.01 and volume > 10000000'
)

print(f"Идеальные акции для инвестирования: {len(ideal_stocks)}")
if len(ideal_stocks) > 0:
    print(ideal_stocks[['company', 'sector', 'daily_return', 'pe_ratio', 'dividend_yield']].round(2))

print(f"\nPandas анализ завершен! Обработано {len(df)} записей.")

=== ЧИСТЫЙ PANDAS АНАЛИЗ ===

1. ЗАГРУЗКА И ОБЗОР ДАННЫХ:
Размер данных: (100, 8)

Информация о данных:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   date            100 non-null    object 
 1   company         100 non-null    object 
 2   sector          100 non-null    object 
 3   open_price      100 non-null    float64
 4   close_price     100 non-null    float64
 5   volume          100 non-null    int64  
 6   pe_ratio        100 non-null    float64
 7   dividend_yield  100 non-null    float64
dtypes: float64(4), int64(1), object(3)
memory usage: 6.4+ KB
None

Первые 5 записей:
         date company  sector  open_price  close_price    volume  pe_ratio  \
0  2024-01-01    MSFT    Auto       80.40    78.416966  43180701     23.33   
1  2024-01-02    AMZN  Retail      263.24   242.385297  13842506     11.09   
2  2024-01-03    MSFT  

In [35]:
def rotation_with_lists(matrix):
    n = len(matrix)
    for i in range(int(len(matrix)/2)):
        for j in range(i, len(matrix) - 1-i):
            temp_1 = a[i][n-j-1]
            a[i][n-j-1] = a[i][j]
            temp_2 = a[n-i-1][n-1-j]
            a[n-i-1][n-1-j] = temp_1
            temp_1 = a[n-i-1][j]
            a[n-i-1][j] = temp_2
            a[i][j] = temp_1
    return matrix

In [36]:
a = [ [2,4,6,8], [1,3,5,7], [10,12,14,16], [9,11,13,15] ]

In [37]:
rotation_with_lists(a)

[[9, 4, 6, 2], [1, 12, 3, 7], [10, 14, 5, 16], [15, 11, 13, 8]]

In [ ]:
#  2  4  6  8
#  1  3  5  7
#  10 12 14 16
#  9  11 13 15
#
# becomes:
#
#  9  10 1  2
#  11 12 3  4
#  13 14 5  6
#  15 16 7  8